### ISSUE TITLE
Split Rewards

### ISSUE THREAD

**Issue by VRRollerCoaster** [vedmant/my-little-bitcoin#4]
Hi, is there any way to implement a main pool that splits rewards based on hashing power, so each user gets a piece of a coin every block regardless if they were the one who mined it or not?
Thanks!

**Comment by vedmant** [comment]
Hi, that's out of scope of simple cryptocurrency implementation. There are existing implementation for pools, like https://github.com/coinfoundry/miningcore https://github.com/sammy007/open-ethereum-pool etc...
